---
version: 2
updates:
  - package-ecosystem: "docker"
    directory: "src"
    schedule:
      interval: "monthly"
    cooldown:
      default-days: 7
    reviewers:
      - "fabasoad"
    labels:
      - "dependencies"
