---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "fabasoad"
    labels:
      - "dependencies"
  - package-ecosystem: "docker"
    directory: "src"
    schedule:
      interval: "monthly"
    reviewers:
      - "fabasoad"
    labels:
      - "dependencies"
