---
name: Security

on: # yamllint disable-line rule:truthy
  pull_request: {}
  push:
    branches:
      - main

defaults:
  run:
    shell: sh

permissions:
  contents: read
  security-events: write

jobs:
  build-image:
    name: Build image
    runs-on: ubuntu-latest
    outputs:
      artifact-name: "${{ steps.artifact.outputs.name }}"
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4
      - name: Get tool versions
        id: versions
        run: |
          echo "hadolint=$(sh ./scripts/get-tool-version.sh -t hadolint)" >> "$GITHUB_OUTPUT"
          echo "actionlint=$(sh ./scripts/get-tool-version.sh -t actionlint)" >> "$GITHUB_OUTPUT"
          echo "pre-commit=$(sh ./scripts/get-tool-version.sh -t pre-commit)" >> "$GITHUB_OUTPUT"
          echo "terraform=$(sh ./scripts/get-tool-version.sh -t terraform)" >> "$GITHUB_OUTPUT"
      - name: Build image
        id: build-image
        uses: docker/build-push-action@v6
        with:
          context: .
          build-args: |
            ARCH=${{ startsWith(runner.arch, 'ARM') && 'arm64' || 'x86_64' }}
            PRE_COMMIT_VERSION=${{ steps.versions.outputs.pre-commit }}
            ACTIONLINT_VERSION=${{ steps.versions.outputs.actionlint }}
            HADOLINT_VERSION=${{ steps.versions.outputs.hadolint }}
            TERRAFORM_VERSION=${{ steps.versions.outputs.terraform }}
          file: src/Dockerfile
          push: false
      - name: Save image
        id: artifact
        run: |
          artifact_name="$(date +%s)"
          archive_path="${RUNNER_TEMP}/${artifact_name}.tar"
          docker save --output "${archive_path}" "${{ steps.build-image.outputs.digest }}"
          echo "path=${archive_path}" >> "$GITHUB_OUTPUT"
          echo "name=${artifact_name}" >> "$GITHUB_OUTPUT"
      - name: Upload artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: "${{ steps.artifact.outputs.name }}"
          path: "${{ steps.artifact.outputs.path }}"
          retention-days: "1"
          compression-level: "0"
  sast:
    name: SAST
    needs: ["build-image"]
    permissions:
      contents: read
      security-events: write
    uses: fabasoad/reusable-workflows/.github/workflows/wf-security-sast.yml@main
    with:
      code-scanning: true
      image: true
      image-artifact-name: "${{ needs.build-image.outputs.artifact-name }}"
      sca: true
