---
name: Security

on: # yamllint disable-line rule:truthy
  pull_request: {}
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      security-type:
        description: What Security scanning you would like to run?
        required: false
        default: "all"
        type: choice
        options: ["all", "sca", "code-scanning", "image"]

defaults:
  run:
    shell: sh

permissions:
  contents: read
  security-events: write

jobs:
  build-image:
    name: Build image
    if: (inputs.security-type || 'all') == 'all' || inputs.security-type == 'image'
    runs-on: ubuntu-latest
    outputs:
      artifact-name: "${{ steps.artifact.outputs.name }}"
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v5
      - name: Get tool versions
        id: versions
        run: |
          {
            echo "hadolint=$(sh ./scripts/get-tool-version.sh -t hadolint)"
            echo "actionlint=$(sh ./scripts/get-tool-version.sh -t actionlint)"
            echo "pre-commit=$(sh ./scripts/get-tool-version.sh -t pre-commit)"
            echo "terraform=$(sh ./scripts/get-tool-version.sh -t terraform)"
          } >> "$GITHUB_OUTPUT"
      - name: Build image
        id: build-image
        uses: docker/build-push-action@v6
        with:
          context: .
          build-args: |
            PRE_COMMIT_VERSION=${{ steps.versions.outputs.pre-commit }}
            ACTIONLINT_VERSION=${{ steps.versions.outputs.actionlint }}
            HADOLINT_VERSION=${{ steps.versions.outputs.hadolint }}
            TERRAFORM_VERSION=${{ steps.versions.outputs.terraform }}
          file: src/Dockerfile
          push: false
      - name: Save image
        id: artifact
        run: |
          artifact_name="$(date +%s)"
          archive_path="${RUNNER_TEMP}/${artifact_name}.tar"
          docker save --output "${archive_path}" "${{ steps.build-image.outputs.digest }}"
          echo "path=${archive_path}" >> "$GITHUB_OUTPUT"
          echo "name=${artifact_name}" >> "$GITHUB_OUTPUT"
      - name: Upload artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: "${{ steps.artifact.outputs.name }}"
          path: "${{ steps.artifact.outputs.path }}"
          retention-days: "1"
          compression-level: "0"
  sast:
    name: SAST
    needs: ["build-image"]
    permissions:
      contents: read
      security-events: write
    uses: fabasoad/reusable-workflows/.github/workflows/wf-security-sast.yml@main
    with:
      code-scanning: ${{ (inputs.security-type || 'all') == 'all' || inputs.security-type == 'code-scanning' }}
      image: ${{ (inputs.security-type || 'all') == 'all' || inputs.security-type == 'image' }}
      image-artifact-name: "${{ needs.build-image.outputs.artifact-name }}"
      sca: ${{ (inputs.security-type || 'all') == 'all' || inputs.security-type == 'sca' }}
